"""Build a self-contained Colab notebook from the reviewed source files."""
import argparse
import json
from pathlib import Path


def build(root,final_run='B',experiments=False):
    cells=[]
    def markdown(text):
        cells.append({'cell_type':'markdown','metadata':{},'source':text.splitlines(keepends=True)})
    def code(text):
        cells.append({'cell_type':'code','metadata':{},'execution_count':None,'outputs':[],'source':text.splitlines(keepends=True)})
    markdown('# NimbusPay: ticket triage on a free Colab T4\n\nUse **Runtime → Change runtime type → T4 GPU**. Upload the original assessment archive when prompted. This notebook contains all training/evaluation code; it never requires public dataset hosting. The default path trains the selected final configuration and regenerates predictions. Other experiments are optional. All displayed scores must come from execution, not estimates.')
    code("import os, time\nos.environ['USE_TF']='0'\nos.environ['USE_FLAX']='0'\nos.environ['TOKENIZERS_PARALLELISM']='false'\nNOTEBOOK_STARTED=time.perf_counter()\n%pip install -q "+' '.join((root/'requirements.txt').read_text().splitlines())+'\n')
    markdown('## Runtime and input setup\n\nThe training stack is pinned. PyTorch/CUDA are provided by the selected Colab runtime and their exact versions are recorded in `environment.json`. The archive and all derived training files remain private. Drive stores checkpoints between sessions; approve its normal account prompt if requested.')
    code(f"RUN_ALL_EXPERIMENTS = {experiments!r}\nFINAL_RUN = {final_run!r}\nUSE_DRIVE_BACKUP = True\n\nimport json, shutil, zipfile, sys\nfrom pathlib import Path\nimport torch\nfrom google.colab import files, drive\nassert torch.cuda.is_available() and 'T4' in torch.cuda.get_device_name(0), 'Free Colab T4 required'\nprint('GPU:',torch.cuda.get_device_name(0),'PyTorch:',torch.__version__,'CUDA:',torch.version.cuda)\nROOT=Path('/content/nimbuspay')\nROOT.mkdir(exist_ok=True)\nos.chdir(ROOT)\nif not Path('private/candidate_pack/data/train.jsonl').exists():\n    uploaded=files.upload()\n    archive=next(name for name in uploaded if name.endswith('.zip'))\n    with zipfile.ZipFile(archive) as z:\n        expected={{'candidate_pack/ASSIGNMENT.md','candidate_pack/SCHEMA.md','candidate_pack/score.py','candidate_pack/data/train.jsonl','candidate_pack/data/dev.jsonl','candidate_pack/data/test_inputs.jsonl'}}\n        assert expected.issubset(set(z.namelist()))\n        for name in expected:\n            path=ROOT/'private'/name\n            path.parent.mkdir(parents=True,exist_ok=True)\n            path.write_bytes(z.read(name))\n    del uploaded\nDATA=ROOT/'private/candidate_pack/data'\nOUT=ROOT/'artifacts'\nif USE_DRIVE_BACKUP:\n    drive.mount('/content/drive')\n    BACKUP=Path('/content/drive/MyDrive/nimbuspay-ticket-triage-private')\n    BACKUP.mkdir(exist_ok=True)\n    OUT=BACKUP/'artifacts'\nelse:\n    BACKUP=None\nSUBMISSION=ROOT/'submission'\nOUT.mkdir(parents=True,exist_ok=True)\n")
    markdown('## Source: auditable training-only cleaning\n\nLabels are corrected by deterministic code and the supplied schema. The repair function is never used for inference. Ambiguous or truncated rows are dropped. Original category/language labels are retained for substantive tickets; the audit does not claim to independently relabel every category.')
    for filename in ['audit.py','score.py','training.py','test_audit.py']:
        code(f'%%writefile {filename}\n'+(root/filename).read_text())
    code("import unittest\nfrom test_audit import AuditTests\nresult=unittest.TextTestRunner(verbosity=2).run(unittest.defaultTestLoader.loadTestsFromTestCase(AuditTests))\nassert result.wasSuccessful()\n")
    markdown('## Audit, sequence lengths, and loss masking\n\nAll examples retain their complete native chat template. The sequence bound is the observed maximum rounded to 128, with dynamic padding. Only assistant-response/end tokens contribute loss. Dev/test are never passed to the training dataset.')
    code("from training import *\ntokenizer, datasets, maximum = prepare(DATA,OUT)\nDEV=load(DATA/'dev.jsonl')\nTEST=load(DATA/'test_inputs.jsonl')\nassert len(DEV)==200 and len(TEST)==400\nassert all(row['id'].startswith('tr-') for rows in datasets.values() for row in rows)\nexample=encode_row(tokenizer,datasets['clean'][0])\nprint('Mask verification:',{'prompt_tokens':example['labels'].count(-100),'supervised_tokens':sum(x!=-100 for x in example['labels']),'sequence_tokens':len(example['input_ids'])})\n")
    markdown('## Baselines and controlled experiments\n\nA is raw QLoRA, B is cleaned QLoRA, C changes precision to FP16 LoRA, D changes only learning rate, and E changes only equivalent input notation. Fixed 160 updates keep optimizer exposure consistent; effective epochs differ when cleaning changes row count. Every run starts from the original base weights. Greedy dev evaluation uses the supplied scorer. A rules-in-prompt baseline is a reference only.')
    code("if RUN_ALL_EXPERIMENTS:\n    if not (OUT/'baseline_rules/result.json').exists():\n        baseline(tokenizer,DEV,OUT,(ROOT/'private/candidate_pack/SCHEMA.md').read_text())\n    for name in ['B','A','C','D','E']:\n        train_run(name,tokenizer,datasets[RUNS[name]['data']],maximum,OUT,DEV)\nelse:\n    # Default reproduction starts a new run directory, never silently reuses an old adapter.\n    OUT=ROOT/f'reproduction_{time.time_ns()}'\n    OUT.mkdir(exist_ok=True)\n    tokenizer,datasets,maximum=prepare(DATA,OUT)\n    train_run(FINAL_RUN,tokenizer,datasets[RUNS[FINAL_RUN]['data']],maximum,OUT,DEV)\n")
    markdown('## Export and reproducibility\n\nInference uses original system/user messages, greedy `model.generate(max_new_tokens=200)`, and whitespace stripping only after normal tokenizer decoding. No fields are repaired. A seeded test sample is regenerated after reloading the adapter. Failed/non-JSON model outputs remain unchanged in the prediction file.')
    code("best=export_best(tokenizer,DEV,TEST,OUT,SUBMISSION)\nprint('Selected run:',json.dumps(best,indent=2))\nprint('Notebook elapsed minutes:',(time.perf_counter()-NOTEBOOK_STARTED)/60)\nassert (time.perf_counter()-NOTEBOOK_STARTED)<3*60*60 or RUN_ALL_EXPERIMENTS, 'Default reproduction exceeded 3 hours'\n# Only code-safe summaries, dev predictions and adapters are exported. Training rows remain private.\nPUBLIC_RESULTS=SUBMISSION/'results'\nPUBLIC_RESULTS.mkdir(exist_ok=True)\nfor path in OUT.rglob('*.json'):\n    if 'checkpoints' not in path.parts and 'adapter' not in path.parts:\n        target=PUBLIC_RESULTS/path.relative_to(OUT)\n        target.parent.mkdir(parents=True,exist_ok=True)\n        shutil.copy2(path,target)\nfor name in RUNS:\n    source=OUT/name/'predictions_dev.jsonl'\n    if source.exists():\n        target=PUBLIC_RESULTS/name/source.name\n        target.parent.mkdir(parents=True,exist_ok=True)\n        shutil.copy2(source,target)\nif BACKUP is not None:\n    shutil.copytree(SUBMISSION,BACKUP/'submission',dirs_exist_ok=True)\narchive=shutil.make_archive('/content/nimbuspay_submission','zip',SUBMISSION)\nfiles.download(archive)\n")
    markdown('## Interpretation and AI disclosure\n\nUse the saved actual dev metrics to analyze weak fields/categories and at least ten specific failures. Peak memory is measured with CUDA allocator counters; training minutes exclude model loading and dev generation. Single-seed comparisons are exploratory. Codex assisted code, audit checks, and report preparation; no external model generated training labels or submitted predictions. The completed report summarizes limitations and a one-week follow-up plan.')
    nb={'nbformat':4,'nbformat_minor':5,'metadata':{'accelerator':'GPU','colab':{'name':'notebook.ipynb','gpuType':'T4'},'kernelspec':{'name':'python3','display_name':'Python 3'},'language_info':{'name':'python'}},'cells':cells}
    (root/'notebook.ipynb').write_text(json.dumps(nb,indent=1))


if __name__=='__main__':
    ap=argparse.ArgumentParser();ap.add_argument('--final-run',default='B');ap.add_argument('--experiments',action='store_true')
    args=ap.parse_args();build(Path(__file__).parent,args.final_run,args.experiments)
